server:
  port: 8083
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.1.174:9092
    consumer:
      enable-auto-commit: true
      group-id: test
      auto-offset-reset: latest
      bootstrap-servers: 192.168.1.174:9092